--CREATE USER TABLE
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE USERS (
    id NUMBER(19) PRIMARY KEY NOT NULL,
    roleId NUMBER(5) NOT NULL,
    firstName VARCHAR2(50) DEFAULT NULL,
    middleName VARCHAR2(50) DEFAULT NULL,
    lastName VARCHAR2(50) DEFAULT NULL,
    username VARCHAR2(50) DEFAULT NULL,
    mobile VARCHAR2(15),
    email VARCHAR2(50),
    passwordHash VARCHAR2(32) NOT NULL,
    registeredAt TIMESTAMP(0) NOT NULL,
    lastLogin TIMESTAMP(0) DEFAULT NULL,
    intro VARCHAR2(255) DEFAULT NULL,
    profile CLOB DEFAULT NULL
);
-- Generate ID using sequence and trigger
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER user_seq_tr BEFORE
INSERT ON USERS FOR EACH ROW
    WHEN (NEW.id IS NULL) BEGIN
SELECT user_seq.NEXTVAL INTO :NEW.id
FROM DUAL;
END;
/ --CREATE TASK TABLE
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE tasks (
    id NUMBER(19) PRIMARY KEY NOT NULL,
    userId NUMBER(19) NOT NULL,
    createdBy NUMBER(19) NOT NULL,
    updatedBy NUMBER(19) NOT NULL,
    title VARCHAR2(512) NOT NULL,
    description VARCHAR2(2048) DEFAULT NULL,
    status NUMBER(5) DEFAULT 0 NOT NULL,
    hours BINARY_DOUBLE DEFAULT 0 NOT NULL,
    createdAt TIMESTAMP(0) NOT NULL,
    updatedAt TIMESTAMP(0) DEFAULT NULL,
    plannedStartDate TIMESTAMP(0) DEFAULT NULL,
    plannedEndDate TIMESTAMP(0) DEFAULT NULL,
    actualStartDate TIMESTAMP(0) DEFAULT NULL,
    actualEndDate TIMESTAMP(0) DEFAULT NULL,
    content CLOB DEFAULT NULL
);
-- Generate ID using sequence and trigger
CREATE SEQUENCE task_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER task_seq_tr BEFORE
INSERT ON tasks FOR EACH ROW
    WHEN (NEW.id IS NULL) BEGIN
SELECT task_seq.NEXTVAL INTO :NEW.id
FROM DUAL;
END;
/ --CREATE TABLE TASK META
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE task_metas (
    id NUMBER(19) PRIMARY KEY NOT NULL,
    taskId NUMBER(19) NOT NULL,
    key VARCHAR2(50) NOT NULL,
    content CLOB DEFAULT NULL
);
-- Generate ID using sequence and trigger
CREATE SEQUENCE task_meta_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER task_meta_seq_tr BEFORE
INSERT ON task_metas FOR EACH ROW
    WHEN (NEW.id IS NULL) BEGIN
SELECT task_meta_seq.NEXTVAL INTO :NEW.id
FROM DUAL;
END;
/ --CREATE TABLE TAG
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE tags (
    id NUMBER(19) PRIMARY KEY NOT NULL,
    title VARCHAR2(75) NOT NULL,
    slug VARCHAR2(100) NOT NULL
);
-- Generate ID using sequence and trigger
CREATE SEQUENCE tag_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER tag_seq_tr BEFORE
INSERT ON tags FOR EACH ROW
    WHEN (NEW.id IS NULL) BEGIN
SELECT tag_seq.NEXTVAL INTO :NEW.id
FROM DUAL;
END;
/ -- CREATE TABLE TASK TAG
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE task_tags (
    taskId NUMBER(19) NOT NULL,
    tagId NUMBER(19) NOT NULL,
    PRIMARY KEY (taskId, tagId)
);
-- CREATE TABLE ACTIVITY
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE activities (
    id NUMBER(19) PRIMARY KEY NOT NULL,
    userId NUMBER(19) NOT NULL,
    taskId NUMBER(19) NOT NULL,
    createdBy NUMBER(19) NOT NULL,
    updatedBy NUMBER(19) NOT NULL,
    title VARCHAR2(512) NOT NULL,
    description VARCHAR2(2048) DEFAULT NULL,
    status NUMBER(5) DEFAULT 0 NOT NULL,
    hours BINARY_DOUBLE DEFAULT 0 NOT NULL,
    createdAt TIMESTAMP(0) NOT NULL,
    updatedAt TIMESTAMP(0) DEFAULT NULL,
    plannedStartDate TIMESTAMP(0) DEFAULT NULL,
    plannedEndDate TIMESTAMP(0) DEFAULT NULL,
    actualStartDate TIMESTAMP(0) DEFAULT NULL,
    actualEndDate TIMESTAMP(0) DEFAULT NULL,
    content CLOB DEFAULT NULL
);
-- Generate ID using sequence and trigger
CREATE SEQUENCE activity_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER activity_seq_tr BEFORE
INSERT ON activities FOR EACH ROW
    WHEN (NEW.id IS NULL) BEGIN
SELECT activity_seq.NEXTVAL INTO :NEW.id
FROM DUAL;
END;
/ -- CREATE TABLE COMMENT
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE comments (
    id NUMBER(19) PRIMARY KEY NOT NULL,
    taskId NUMBER(19) NOT NULL,
    activityId NUMBER(19) DEFAULT NULL,
    title VARCHAR2(100) NOT NULL,
    createdAt TIMESTAMP(0) NOT NULL,
    updatedAt TIMESTAMP(0) DEFAULT NULL,
    content CLOB DEFAULT NULL
);
-- Generate ID using sequence and trigger
CREATE SEQUENCE comment_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER comment_seq_tr BEFORE
INSERT ON comments FOR EACH ROW
    WHEN (NEW.id IS NULL) BEGIN
SELECT comment_seq.NEXTVAL INTO :NEW.id
FROM DUAL;
END;
/ -- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE UNIQUE INDEX uq_username ON "USERS" (username);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE UNIQUE INDEX uq_mobile ON "USERS" (mobile);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE UNIQUE INDEX uq_email ON "USERS" (email);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX idx_task_user ON tasks (userId);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX idx_meta_task ON task_metas (taskId);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE UNIQUE INDEX uq_task_meta ON task_metas (taskId, key);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX idx_tt_task ON task_tags (taskId);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX idx_tt_tag ON task_tags (tagId);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX idx_activity_user ON activities (userId);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX idx_comment_task ON comments (taskId);
ALTER TABLE tasks
ADD CONSTRAINT fk_task_user FOREIGN KEY (userId) REFERENCES "USERS" (id);
ALTER TABLE tasks
ADD FOREIGN KEY (createdBy) REFERENCES "USERS" (id);
ALTER TABLE tasks
ADD FOREIGN KEY (updatedBy) REFERENCES "USERS" (id);
ALTER TABLE task_metas
ADD CONSTRAINT fk_meta_task FOREIGN KEY (taskId) REFERENCES tasks (id);
ALTER TABLE task_tags
ADD CONSTRAINT fk_tt_task FOREIGN KEY (taskId) REFERENCES tasks (id);
ALTER TABLE task_tags
ADD CONSTRAINT fk_tt_tag FOREIGN KEY (tagId) REFERENCES tags (id);
ALTER TABLE activities
ADD CONSTRAINT fk_activity_user FOREIGN KEY (userId) REFERENCES "USERS" (id);
ALTER TABLE activities
ADD FOREIGN KEY (taskId) REFERENCES tasks (id);
ALTER TABLE activities
ADD FOREIGN KEY (createdBy) REFERENCES "USERS" (id);
ALTER TABLE activities
ADD FOREIGN KEY (updatedBy) REFERENCES "USERS" (id);
ALTER TABLE comments
ADD CONSTRAINT fk_comment_task FOREIGN KEY (taskId) REFERENCES tasks (id);
ALTER TABLE comments
ADD FOREIGN KEY (activityId) REFERENCES activities (id);